# 資料前處理(Label encoding、 One hot encoding)
這兩個編碼方式的目的是為了將類別 (categorical)或是文字(text)的資料轉換成數字，而讓程式能夠更好的去理解及運算。
> Label encoding : 把每個類別 mapping 到某個整數，不會增加新欄位

> One hot encoding : 為每個類別新增一個欄位，用 0/1 表示是否

![](images/Encoder.PNG)


## Encoding Categorical features (or label)
![](images/Encoding.PNG)


In [6]:
import pandas as pd
import numpy as np


In [7]:
df = pd.DataFrame({'blood':['A','B','AB','O','B'], 
                   'Y':['high','low','high','mid','mid'],
                   'Z':[np.nan,np.nan,-1196,72,83]});
df

,blood,Y,Z
0,A,high,NaN
1,B,low,NaN
2,AB,high,-1196.0
3,O,mid,72.0
4,B,mid,83.0


# 方法一：sklearn - label encoder + onehot encoder
>onehot encoder要用2D array，若維度所以要用reshape(-1,1)<br>
>onehot encoder要數字，若資料文文字要先用label encoder轉數字

In [3]:
!pip install keras tensorflow


[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import sys
!{sys.executable} -m pip install keras tensorflow

  Using cached keras-3.14.0-py3-none-any.whl.metadata (6.3 kB)


ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: C:\Users\User\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for tensorflow


In [3]:
import sys
!{sys.executable} -m pip install scikit-learn pandas

  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ------- -------------------------------- 1.6/8.1 MB 11.6 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.1 MB 16.3 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 15.4 MB/s  0:00:00
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ---- ----------------------------------- 4.2/37.3 MB 19.7 MB/s eta 0:00:02
   -------- ------------------------------- 8.1/37.3 MB 18.9 MB/s eta 0:00:02
   ------------ --------------------------- 11.8/37.3 MB 18.5 MB/s eta 0:00:02
   ---------------- ----------------------- 15.5/37.3 MB 18.5 MB/s eta 0:00:02
   --------------------- ------------------ 19.7/37.3 MB 18.6 MB/s eta 0:00:01
   ------------------------- -------------- 23.6/37.3 MB


[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: C:\Users\User\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip


In [44]:
#label encoder

#from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn import datasets
from sklearn.model_selection import train_test_split


# 初始化 LabelEncoder
encoder = LabelEncoder()
# 將類別標籤 Y 轉換為整數編碼
encoded_blood = encoder.fit_transform(df['blood'])

print(df['blood'])
print(encoded_blood)

# 將整數編碼轉換為虛擬變數 (One-hot encoding)
# convert integers to dummy variables (one hot encoding)
#dummy_blood = np_utils.to_categorical(encoded_blood) # one-hot encoding [0. 1. 0.]
#print(dummy_y)

0     A
1     B
2    AB
3     O
4     B
Name: blood, dtype: object
[0 2 1 3 2]


In [19]:
oh_encoder = OneHotEncoder(sparse_output=False)
dummy_blood = oh_encoder.fit_transform(encoded_blood.reshape(-1, 1))
print(dummy_blood)

[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


## One hot encoding
One Hot encoding的編碼邏輯為將類別拆成多個行(column)，每個列中的數值由1、0替代，當某一列的資料存在的該行的類別則顯示1，反則顯示0。

然在指定column進行編碼的情形下，One hot encoding<b>無法直接對字串進行編碼，必須先透過Label encoding將字串以數字取代後再進行One hot encoding處理。</b>

> categorical_features = [0]: 表示欲在data上執行One hot encoding的index為0

> data_le: 為經過Label encoding編碼的資料(註:OneHotEncoder的輸入要為2-D array，而Label encoding為1-D array)


OneHotEncoder會轉出scipy.csr_matrix資料結構用.toarray()轉array
從結果可以知道，數字0的column 代表的是A、數字1的column 代表的是B，而數字2的column 代表的是AB。
除了轉換字串外，One hot encoding也可以轉換數字。在此處的data就不需要先經過Label encoding編碼

```python
# importing one hot encoder from sklearn 
# There are changes in OneHotEncoder class 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 
   
# creating one hot encoder object with categorical feature 0 
# indicating the first column 
columnTransformer = ColumnTransformer([('encoder', 
                                        OneHotEncoder(), 
                                        [0])], 
                                      remainder='passthrough') 
  
data = np.array(columnTransformer.fit_transform(data), dtype = str) 
```

In [22]:
# importing one hot encoder from sklearn 
# There are changes in OneHotEncoder class 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 

# creating one hot encoder object with categorical feature 0 
# indicating the first column 
columnTransformer = ColumnTransformer([('encoder', 
                                        OneHotEncoder(), 
                                        [0])], 
                                      remainder='passthrough') 

data = np.array(columnTransformer.fit_transform(df), dtype = str)
print(data)

[['1.0' '0.0' '0.0' '0.0' 'high' 'nan']
 ['0.0' '0.0' '1.0' '0.0' 'low' 'nan']
 ['0.0' '1.0' '0.0' '0.0' 'high' '-1196.0']
 ['0.0' '0.0' '0.0' '1.0' 'mid' '72.0']
 ['0.0' '0.0' '1.0' '0.0' 'mid' '83.0']]


# 方法二：Keras - label encoder + to_categorical
>to_categorical要數字，若資料文文字要先用label encoder轉數字

In [23]:
!pip install keras-core numpy

   ---------------------------------------- 0.0/950.8 kB ? eta -:--:--
   ---------------------- ----------------- 524.3/950.8 kB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 950.8/950.8 kB 7.3 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [27]:
import sys
!{sys.executable} -m pip install keras-core

  Using cached keras_core-0.1.7-py3-none-any.whl.metadata (4.3 kB)
  Using cached absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Using cached keras_core-0.1.7-py3-none-any.whl (950 kB)
Using cached absl_py-2.4.0-py3-none-any.whl (135 kB)
   ---------------------------------------- 0.0/3.2 MB ? eta -:--:--
   ----------------------------- ---------- 2.4/3.2 MB 13.3 MB/s eta 0:00:01
   ---------------------------------------- 3.2/3.2 MB 9.3 MB/s  0:00:00
Using cached namex-0.1.0-py3-none-any.whl (5.9 kB)

   ------------- -------------------------- 2/6 [h5py]
   ------------- -------------------------- 2/6 [h5py]
   ------------- -------------------------- 2/6 [h5py]
   ------------- -------------------------- 2/6 [h5py]
   -------------------- ------------------- 3/6 [absl-py]
   --------------------------------- ------ 5/6 [keras-core]
   --------------------------------- ------ 5/6 [keras-core]
   ---------------------


[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: C:\Users\User\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip


In [24]:
import os
os.environ["KERAS_BACKEND"] = "numpy"

In [28]:
from sklearn.preprocessing import LabelEncoder   #3.14 版本無法安裝
import keras_core as keras
#from keras.utils import np_utils

df = pd.DataFrame({'blood':['A','B','AB','O','B'], 
                   'Y':['high','low','high','mid','mid'],
                   'Z':[np.nan,np.nan,-1196,72,83]});

# label encoder 


# convert integers to one hot encoding




Using NumPy backend.
The NumPy backend does not support training. It should only be used for inference, evaluation, and debugging.


ModuleNotFoundError: No module named 'jax'

## 方法三：pd.get_dummies方法
![](images/Encoding_pd.PNG)
pd.get_dummies(df)
>get_dummies可以直接轉字串，反而無法轉換數字<br>
>get_dummies沒指定columns，會全部轉換

In [31]:
df = pd.DataFrame({'blood':['A','B','AB','O','B'], 
                   'Y':['high','low','high','mid','mid'],
                   'Z':[np.nan,np.nan,-1196,72,83]})

df_blood_oh = pd.get_dummies(df['blood'], dtype=float)
final_df = pd.concat([df_blood_oh, df[['Y', 'Z']]], axis=1)
print(final_df)

     A   AB    B    O     Y       Z
0  1.0  0.0  0.0  0.0  high     NaN
1  0.0  0.0  1.0  0.0   low     NaN
2  0.0  1.0  0.0  0.0  high -1196.0
3  0.0  0.0  0.0  1.0   mid    72.0
4  0.0  0.0  1.0  0.0   mid    83.0


In [30]:
df_encoded = pd.get_dummies(df)
print(df_encoded)

        Z  blood_A  blood_AB  blood_B  blood_O  Y_high  Y_low  Y_mid
0     NaN     True     False    False    False    True  False  False
1     NaN    False     False     True    False   False   True  False
2 -1196.0    False      True    False    False    True  False  False
3    72.0    False     False    False     True   False  False   True
4    83.0    False     False     True    False   False  False   True


## 練習一：sklearn - label encoder + onehot encoder
下面的資料可以看到country那欄皆為字串， 大部分的模型都是基於數學運算，字串無法套入數學模型進行運算，<br>
在此先對其進行Label encoding編碼，我們從 sklearn library中導入 LabelEncoder class，對第一行資料進行fit及transform並取代之。

In [33]:
import numpy as np
import pandas as pd
country=['Taiwan','Australia','Ireland','Australia','Ireland','Taiwan']
age=[25,30,45,35,22,36]
salary=[20000,32000,59000,60000,43000,52000]
dic={'Country':country,'Age':age,'Salary':salary}
data01=pd.DataFrame(dic)
data01

,Country,Age,Salary
0,Taiwan,25,20000
1,Australia,30,32000
2,Ireland,45,59000
3,Australia,35,60000
4,Ireland,22,43000
5,Taiwan,36,52000


In [34]:
columnTransformer = ColumnTransformer([('encoder', 
                                        OneHotEncoder(), 
                                        [0])], 
                                      remainder='passthrough') 

data01_fin = np.array(columnTransformer.fit_transform(data01), dtype = str)
print(data01_fin)

[['0.0' '0.0' '1.0' '25.0' '20000.0']
 ['1.0' '0.0' '0.0' '30.0' '32000.0']
 ['0.0' '1.0' '0.0' '45.0' '59000.0']
 ['1.0' '0.0' '0.0' '35.0' '60000.0']
 ['0.0' '1.0' '0.0' '22.0' '43000.0']
 ['0.0' '0.0' '1.0' '36.0' '52000.0']]


## 練習二：Keras - label encoder + to_categorical

In [ ]:
from sklearn.preprocessing import LabelEncoder   #python 3.14版無法使用
from keras.utils import np_utils

country=['Taiwan','Australia','Ireland','Australia','Ireland','Taiwan']
age=[25,30,45,35,22,36]
salary=[20000,32000,59000,60000,43000,52000]
dic={'Country':country,'Age':age,'Salary':salary}
data02=pd.DataFrame(dic)
data

## 練習三：Pandas.get_dummies
>　get_dummies : 僅能將字串轉換為One hot encoding表示形式， 沒指定columns會全部轉換。

In [38]:
country=['Taiwan','Australia','Ireland','Australia','Ireland','Taiwan']
age=[25,30,45,35,22,36]
salary=[20000,32000,59000,60000,43000,52000]
dic={'Country':country,'Age':age,'Salary':salary}
data01=pd.DataFrame(dic)
data01

,Country,Age,Salary
0,Taiwan,25,20000
1,Australia,30,32000
2,Ireland,45,59000
3,Australia,35,60000
4,Ireland,22,43000
5,Taiwan,36,52000


In [39]:
data01_country_oh = pd.get_dummies(data01['Country'], dtype=float)
final_data01 = pd.concat([data01_country_oh, data01[['Age', 'Salary']]], axis=1)
print(final_data01)

   Australia  Ireland  Taiwan  Age  Salary
0        0.0      0.0     1.0   25   20000
1        1.0      0.0     0.0   30   32000
2        0.0      1.0     0.0   45   59000
3        1.0      0.0     0.0   35   60000
4        0.0      1.0     0.0   22   43000
5        0.0      0.0     1.0   36   52000
